/**
 * Embed content/blog/*.md into a TypeScript module the Worker can import.
 * Markdown files remain the CMS. This script is the only fs reader.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const blogDir = join(root, "content/blog");
const outFile = join(root, "src/lib/blog-data.generated.ts");

function isSkippedBlogFile(filename: string): boolean {
  if (!filename.endsWith(".md")) return true;
  if (filename.startsWith("_")) return true;
  if (filename.toLowerCase() === "readme.md") return true;
  return false;
}

const sources = readdirSync(blogDir)
  .filter((filename) => !isSkippedBlogFile(filename))
  .sort((a, b) => a.localeCompare(b))
  .map((filename) => ({
    slug: filename.slice(0, -3),
    raw: readFileSync(join(blogDir, filename), "utf8"),
  }));

const contents = `/** Generated by scripts/embed-blog.ts. Do not edit by hand. */

export const BLOG_SOURCES: { slug: string; raw: string }[] = ${JSON.stringify(sources, null, 2)};
`;

writeFileSync(outFile, contents);
console.log(`Wrote ${sources.length} post(s) to ${outFile}`);
